YourBook/urls.py
from django.urls import path
from YourBook.views import *
app_name = 'YourBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('logout/', logout_user, name='logout'),
    path('get-product/<str:filter>', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('get_jumlah_item/', get_jumlah_item, name='get_jumlah_item'),
    path('get-product-flutter/', get_product_json_flutter, name='get_product_json_flutter'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
     path('delete-flutter/', delete_item_flutter, name='delete_product_flutter'),
]

bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_bookmark', add_bookmark, name='add_bookmark'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('create-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('remove-bookmark/<int:item_id>', remove_bookmark, name='remove_bookmark'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

gourmet_labs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('YourBook/', include('YourBook.urls')),
    path('review/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
    path("api/books/", include("main.urls")),
    path('publication/', include('publication.urls')), 
    path('bookmark/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_awal, name='show_awal'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('main/', show_main, name='show_main'),
    path("api/books/", get_books, name="get_books"),
    path("add-product-ajax/", add_product_ajax, name="add_product_ajax"),
    path("get-user/", get_user, name="get_user"),
    path("get-buku/", get_buku, name="get_buku"),
     path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

review/urls.py
from django.urls import path
from review.views import *

app_name = 'review'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

wishlist/urls.py
from wishlist.views import show_main, add_wishlist, show_xml, show_json, show_json_by_id, show_xml_by_id, remove_wishlist, add_wishlist_ajax, get_wishlist_json, logout_user, create_wishlist_flutter, delete_wishlist_flutter
from django.urls import path

app_name = 'wishlist'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-wishlist', add_wishlist, name='add_wishlist'),
    path('xml/', show_xml, name='show_xml'), 
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('remove-wishlist/<int:item_id>', remove_wishlist, name='remove_wishlist'), 
    path('create-wishlist-ajax/', add_wishlist_ajax, name='add_wishlist_ajax'),
    path('get-wishlist/', get_wishlist_json, name='get_wishlist_json'),
    path('create-flutter/', create_wishlist_flutter, name='create_wishlist_flutter'),
    path('delete_wishlist_flutter/', delete_wishlist_flutter, name='delete_wishlist_flutter'),
]

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(null=True, blank=True)
    description = models.TextField()    

bookmark/forms.py
from django.forms import ModelForm
from bookmark.models import *

class BookmarkForm(ModelForm):
    class Meta:
        model = Bookmark
        fields = ["title","description"]

bookmark/views.py
import json
from django.shortcuts import get_object_or_404, redirect, render
from .models import Bookmark
from bookmark.forms import BookmarkForm
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='login/')
def show_main(request):
    Books = Bookmark.objects.all()

    context = {
        'books': Books,
        'name': request.user.username,
    }

    return render(request, "bookmark.html", context)

def add_bookmark(request):
    form = BookmarkForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        wishlist_item = form.save(commit=False)
        wishlist_item.user = request.user
        wishlist_item.save()
        return HttpResponseRedirect(reverse('bookmark:show_main'))

    context = {'form': form}
    return render(request, "add_bookmark.html", context)

def show_xml(request):
    data = Bookmark.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Bookmark.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Bookmark.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Bookmark.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_bookmark_json(request):
    bookmark_item = Bookmark.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', bookmark_item))

@csrf_exempt
def add_bookmark_ajax(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        description = request.POST.get("description")
        user = request.user

        new_bookmark = Bookmark(title=title, description=description, user=user)
        new_bookmark.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def remove_bookmark(request, item_id):
    bookmark = Bookmark.objects.get(id = item_id)
    bookmark.delete()
    
    return HttpResponseRedirect(reverse('bookmark:show_main'))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Bookmark.objects.create(
            user = request.user,
            title = data["title"],
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

bookmark/templates/add_bookmark.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Bookmark"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

bookmark/templates/bookmark.html
{% extends 'base.html' %} 
{% block content %}
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="font-weight: bolder;">GourmetLabs</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
            </li>
        </div>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-right">
              <li class="nav-item">
                  <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal1">About Us</a>
              </li>
          </ul>
        </div>
      
        <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content text-white" style="background-color:tan; border-radius: 10px;">
              <div class="modal-header border-bottom-0">
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-start px-4 pt-0 pb-4">
                <div class="text-center">
                  <h3 class="mb-3">About GourmetLabs</h3>
                  <h5 class="mb-5" style="font-weight:lighter">GourmetLabs is an application that provides information, recipes, and engaging reading experiences about culinary cultures from various countries, allowing users to enjoy exclusive culinary-related content.</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
  
  
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown link
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'YourBook:show_main' %}">Pinjam Buku</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="{% url 'review:show_main' %}">Review</a></li>
                <li><a class="dropdown-item" href="{% url 'wishlist:show_main' %}">Wishlist</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  
    <section id="header">
      <div class="d-flex justify-content-center align-items-center mt-5">
        <h3>{{ name }}'s bookmarks</h3>
      </div>
      <hr class="border border-dark border-2 opacity-50">
    </section>


    <!-- AJAX MODEL -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">New Bookmark</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form id="form" onsubmit="return false;">
                      {% csrf_token %}
                      <div class="mb-3">
                          <label for="title" class="col-form-label">Book Title:</label>
                          <input type="text" class="form-control" id="title" name="title"></input>
                      </div>
                      <div class="mb-3">
                          <label for="description" class="col-form-label">Description:</label>
                          <input type="text" class="form-control" id="description" name="description"></input>
                      </div>
                  </form>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
              </div>
          </div>
      </div>
    </div>

    <div class="d-flex flex-row">
      <div id="bookmark-card" class="d-flex flex-wrap"></div>
    </div>
    
    
    <div class="d-flex flex-row justify-content-center align-items-center">
      <a href="{% url 'bookmark:add_bookmark' %}">
        <button type="button" class="btn btn-secondary m-5">
            Add Bookmark
        </button>
      </a>
      <button type="button" class="btn btn-primary " data-bs-toggle="modal" data-bs-target="#exampleModal">Add Bookmark by AJAX</button>
    </div>
  </div>


  <script>
    async function getBookmark() {
      return fetch("{% url 'bookmark:get_bookmark_json' %}").then((res) => res.json())
    }

    async function deleteBookmark(id) {
      const response = await fetch(`remove-bookmark/${id}`);
      refreshBookmark();
    }

    function addBookmark() {
        fetch("{% url 'bookmark:add_bookmark_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshBookmark)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addBookmark

    async function refreshBookmark() {
        document.getElementById("bookmark-card").innerHTML = ""
        const bookmark = await getBookmark()
        let htmlString = ``

        bookmark.forEach((item) => {
            htmlString += `\n
            <div class="card m-2" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">${ item.fields.title }</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">${ item.fields.description }</h6>
                <button onclick="deleteBookmark(${item.pk})" type="submit" class="btn btn-danger">delete bookmark</button>
              </div>
            </div>` 
        })
        
        document.getElementById("bookmark-card").innerHTML = htmlString
    }

    refreshBookmark()

    
  </script>
</body>


{% endblock %}