Publication/urls.py
from django.urls import path
from Publication.views import new_publication

app_name = 'main'

urlpatterns = [
    path('publication', new_publication, name='new_publication'),
]

YourBook/urls.py
from django.urls import path
from YourBook.views import *
app_name = 'YourBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('logout/', logout_user, name='logout'),
    path('get-product/<str:filter>', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('get_jumlah_item/', get_jumlah_item, name='get_jumlah_item'),
    path('get-product-flutter/', get_product_json_flutter, name='get_product_json_flutter'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
     path('delete-flutter/', delete_item_flutter, name='delete_product_flutter'),
]

bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_bookmark', add_bookmark, name='add_bookmark'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('create-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('remove-bookmark/<int:item_id>', remove_bookmark, name='remove_bookmark'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

gourmet_labs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('YourBook/', include('YourBook.urls')),
    path('review/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
    path("api/books/", include("main.urls")),
    path('publication/', include('publication.urls')), 
    path('bookmark/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_awal, name='show_awal'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('main/', show_main, name='show_main'),
    path("api/books/", get_books, name="get_books"),
    path("add-product-ajax/", add_product_ajax, name="add_product_ajax"),
    path("get-user/", get_user, name="get_user"),
    path("get-buku/", get_buku, name="get_buku"),
     path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

publication/urls.py
from django.urls import path
from publication.views import *

app_name = 'publication'

urlpatterns = [
    path('your-publication/', show_main, name='show_main'),
    path('publication/', new_publication, name='new_publication'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('add-publication-ajax/', new_publication_ajax, name="new_publication_ajax"),
    path('get-buku-user/', get_buku_user, name="get_buku_user"),
    path('new-publication-flutter/', new_publication_flutter, name="new_publication_flutter"),
]

review/urls.py
from django.urls import path
from review.views import *

app_name = 'review'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

wishlist/urls.py
from wishlist.views import show_main, add_wishlist, show_xml, show_json, show_json_by_id, show_xml_by_id, remove_wishlist, add_wishlist_ajax, get_wishlist_json, logout_user, create_wishlist_flutter, delete_wishlist_flutter
from django.urls import path

app_name = 'wishlist'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-wishlist', add_wishlist, name='add_wishlist'),
    path('xml/', show_xml, name='show_xml'), 
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('remove-wishlist/<int:item_id>', remove_wishlist, name='remove_wishlist'), 
    path('create-wishlist-ajax/', add_wishlist_ajax, name='add_wishlist_ajax'),
    path('get-wishlist/', get_wishlist_json, name='get_wishlist_json'),
    path('create-flutter/', create_wishlist_flutter, name='create_wishlist_flutter'),
    path('delete_wishlist_flutter/', delete_wishlist_flutter, name='delete_wishlist_flutter'),
]

Publication/models.py
from django.db import models
# from YourBook.models import Products
# Create your models here.

class Book(models.Model):
    # book = models.ForeignKey(Products, on_delete=models.CASCADE)
    author = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    publish_date = models.DateField(auto_now_add=True)
    description = models.TextField()

publication/models.py
from django.db import models
from main.models import Buku
from django.contrib.auth.models import User

# Create your models here.

class Publication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # book = models.ForeignKey(Buku, on_delete=models.CASCADE)
    author = models.TextField(null=True)
    title = models.TextField(null=True)
    issued = models.DateField(auto_now_add=True, null=True)
    subjects = models.TextField(null=True)
    language = models.TextField(null=True)
    bookshelves = models.TextField(default="Cookbooks and Cooking")
    locc = models.TextField(default="TX")

Publication/forms.py
from django.forms import ModelForm
from Publication.models import Book

class NewPublicationForm(ModelForm):
    class Meta:
        model = Book
        fields = ["author", "title", "description"]

publication/forms.py
from django.forms import ModelForm, HiddenInput
from publication.models import Publication
from django import forms

class NewPublicationForm(ModelForm):
    class Meta:
        model = Publication
        fields = ["author", "title", "subjects", "language", "bookshelves", "locc"]
        widgets = {
            "author": forms.TextInput(attrs={"required": True}),
            "title": forms.TextInput(attrs={"required": True}),
            "issued": HiddenInput(),
        }

Publication/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from Publication.forms import NewPublicationForm

def new_publication(request):
    form = NewPublicationForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        book = form.save(commit=False)
        book.user = request.user
        book.save()
        return HttpResponseRedirect(reverse('Publication:show_main'))
    
    context = {'form' : form}
    return render(request, "publication.html", context)

publication/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from publication.forms import NewPublicationForm
from publication.models import Publication
from main.models import Buku
from django.views.decorators.csrf import csrf_exempt
import json

@login_required(login_url='login/')
def show_main(request):
    books = Publication.objects.filter(user=request.user)
    
    context = {
        'account': request.user.username,
        'books': books,
    }
    return render(request, "your_publication.html", context)

def new_publication(request):
    form = NewPublicationForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        # Ambil data dari formulir
        author = form.cleaned_data['author']
        title = form.cleaned_data['title']
        subjects = form.cleaned_data['subjects']
        language = form.cleaned_data['language']
        bookshelves = form.cleaned_data['bookshelves']
        locc = form.cleaned_data['locc']

        # Simpan objek Buku terlebih dahulu
        book = Buku.objects.create(
            Authors=author,
            Title=title,
            Subjects=subjects,
            Language=language,
            # Issued=issued,
            Bookshelves=bookshelves,
            LoCC=locc
        )

        with open('main/fixtures/books.json', 'r') as file:
            dataset = json.load(file)

        dataset.append({
            "pk": book.pk,
            "model": "main.buku",
            "fields": {
                "Text": "-",
                "Type": "Text",
                "Issued": book.Issued,
                "Title": book.Title,
                "Language": book.Language,
                "Authors": book.Authors,
                "Subjects": book.Subjects,
                "LoCC": "TX",
                "Bookshelves": "Cookbooks and Cooking",
            }
        })
        
        with open('main/fixtures/books.json', 'w') as file:
                json.dump(dataset, file, indent=4)

        buku = form.save(commit=False)
        buku.user = request.user
        buku.save()
        return HttpResponseRedirect(reverse('publication:show_main'))
    
    context = {'form' : form}
    return render(request, "publication.html", context)

@csrf_exempt
def new_publication_ajax(request):
    if request.method == 'POST':
        author = request.POST.get("author")
        title = request.POST.get("title")
        subjects = request.POST.get("subjects")
        language = request.POST.get("language")
        bookshelves = request.POST.get("bookshelves")
        locc = request.POST.get("locc")
        user = request.user

        # Simpan objek Buku terlebih dahulu
        book = Publication.objects.create(
            user=user,
            author=author,
            title=title,
            subjects=subjects,
            language=language,
            bookshelves=bookshelves,
            locc=locc
        )

        with open('main/fixtures/books.json', 'r') as file:
            dataset = json.load(file)

        dataset.append({
            "pk": book.pk,
            "model": "main.buku",
            "fields": {
                "Text": "-",
                "Type": "Text",
                "Issued": book.Issued,
                "Title": book.Title,
                "Language": book.Language,
                "Authors": book.Authors,
                "Subjects": book.Subjects,
                "LoCC": book.locc,
                "Bookshelves": book.bookshelves,
            }
        })

        with open('main/fixtures/books.json', 'w') as file:
            json.dump(dataset, file, indent=4)

        # book = Publication(user = user, author = author, title = title, subjects = subjects, language = language, bookshelves = bookshelves, locc = locc)
        book.save()

        return HttpResponse(b"CREATED", status=201)
    
    # Mengembalikan respons JSON dengan status gagal jika permintaan bukan metode POST atau formulir tidak valid
    return HttpResponseNotFound()

def show_xml(request):
    data = Publication.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Publication.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Publication.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Publication.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def get_buku_user(request):
    product_item = Publication.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def new_publication_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        book = Publication.objects.create(
            user = request.user,
            author=data["author"],
            title=data["title"],
            subjects=data["subjects"],
            language=data["language"],
            issued=data["issued"],
            bookshelves=data["bookshelves"],
            locc=data["locc"],
        )

        with open('main/fixtures/books.json', 'r') as file:
            dataset = json.load(file)

        dataset.append({
            "pk": book.pk,
            "model": "main.buku",
            "fields": {
                "Text": "-",
                "Type": "Text",
                "Issued": book.issued,
                "Title": book.title,
                "Language": book.language,
                "Authors": book.author,
                "Subjects": book.subjects,
                "LoCC": book.locc,
                "Bookshelves": book.bookshelves,
            }
        })
        
        with open('main/fixtures/books.json', 'w') as file:
                json.dump(dataset, file, indent=4)

        book.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
# temp

publication/templates/publication.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/new-pub.css' %}">
{% endblock meta %}

{% block content %}
<style>
    .navbar {
        border-radius: 50px;
    }
    .navbar-nav .nav-link:hover {
        background-color: lightgrey;
    }

    body {
      background-image: url('https://i.ibb.co/nQYv36L/abstract-smooth-blur-background-backdrop-for-your-design-wallpaper-template-with-color-transition-gr.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
      justify-content: center;
      text-align: center;
      align-items: center;
      font-family: Georgia, 'Times New Roman', Times, serif;
    }

    .input {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin: 0 auto;
        text-align: center;
    }

    .input-box {
        display: table-column;
        width: 450px;
        height: 450px;
        padding: 30px;
        background-color: whitesmoke;
        border: 1px solid whitesmoke;
        border-radius: 15px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        text-align: center;
        margin: 5%;
    }

    .input-place {
        display: flex;
        text-align: center;
        justify-content: center;
        align-items: center;
    }

    #input-table {
        border-collapse: separate;
        border-spacing: 5px;
    }

    #submit-btn {
        background-color: white;

        padding: 5px 15px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 20px;
        align-items: center;
    }
</style>

<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:show_main' %}" style="font-weight: bolder;">GourmetLabs</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-right">
                <li class="nav-item">
                  <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal1">Add role</a>
                </li>
            </ul>
          </div>

          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Navigation
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:show_main' %}">Home</a></li>
                  <li><a class="dropdown-item" href="{% url 'YourBook:show_main' %}">Pinjam Buku</a></li>
                  <li><a class="dropdown-item" href="{% url 'review:show_main' %}">Review</a></li>
                  <li><a class="dropdown-item" href="{% url 'wishlist:show_main' %}">Wishlist</a></li>
                  <li><a class="dropdown-item" href="{% url 'publication:show_main' %}">Publish</a></li>
                  <li><a class="dropdown-item" href="{% url 'bookmark:show_main' %}">Bookmark</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
        <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content text-white" style="background-color:grey; border-radius: 10px;">
              <div class="modal-header border-bottom-0">
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-start px-4 pt-0 pb-4">
                <div class="modal-body">
                  <form id="form" onsubmit="return false;">
                      {% csrf_token %}
                      <label>
                        <input type="radio" name="role" value="user" checked>
                        User
                      </label>
                      <label>
                        <input type="radio" name="role" value="admin">
                        Admin
                      </label>
                  </form>
                  <p>User tidak dapat memilih ulang role jika sebelumnya sudah memilih!   </p>
              </div>
              <div class="modal-footer">
                  <button type="submit" id="button_add">Select Role</button>
              </div>
              </div>
            </div>
          </div>
        </div>
      </nav>
</div>

<div class="input">
    <div class="input-box">
        <h1 style="font-weight: bolder;" class="title-page">Book's Data</h1>
        <br>
        <form method="POST">
            <div class="input-place">
                {% csrf_token %}
                <table id="input-table">
                    {{ form.as_table }}
                </table>
            </div>
            <br><br>
            <input id="submit-btn" type="submit" value="Publish"/>
        </form>
    </div>
</div>
{% endblock %}

publication/templates/your_publication.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/your-pub.css' %}">
{% endblock meta %}

{% block content %}
<style>
    .navbar {
        border-radius: 50px;
    }
    .navbar-nav .nav-link:hover {
        background-color: lightgrey;
    }

    body {
      background-image: url('https://i.ibb.co/nQYv36L/abstract-smooth-blur-background-backdrop-for-your-design-wallpaper-template-with-color-transition-gr.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
      justify-content: center;
      text-align: center;
      align-items: center;
    }

</style>

<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:show_main' %}" style="font-weight: bolder;">GourmetLabs</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-right">
                <li class="nav-item">
                  <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal1">Add role</a>
                </li>
            </ul>
          </div>

          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Navigation
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:show_main' %}">Home</a></li>
                  <li><a class="dropdown-item" href="{% url 'YourBook:show_main' %}">Pinjam Buku</a></li>
                  <li><a class="dropdown-item" href="{% url 'review:show_main' %}">Review</a></li>
                  <li><a class="dropdown-item" href="{% url 'wishlist:show_main' %}">Wishlist</a></li>
                  <li><a class="dropdown-item" href="{% url 'publication:show_main' %}">Publish</a></li>
                  <li><a class="dropdown-item" href="{% url 'bookmark:show_main' %}">Bookmark</a></li>
                  <li><a class="dropdown-item" href="{% url 'YourBook:logout' %}">Logout</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
        <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content text-white" style="background-color:grey; border-radius: 10px;">
              <div class="modal-header border-bottom-0">
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-start px-4 pt-0 pb-4">
                <div class="modal-body">
                  <form id="form" onsubmit="return false;">
                      {% csrf_token %}
                      <label>
                        <input type="radio" name="role" value="user" checked>
                        User
                      </label>
                      <label>
                        <input type="radio" name="role" value="admin">
                        Admin
                      </label>
                  </form>
                  <p>User tidak dapat memilih ulang role jika sebelumnya sudah memilih!   </p>
              </div>
              <div class="modal-footer">
                  <button type="submit" id="button_add">Select Role</button>
              </div>
              </div>
            </div>
          </div>
        </div>
      </nav>

<br>

<div class="collection-info">
    You published {{ books_count }} books in GourmetLabs
</div>

<table id="product_table"></table>

<!-- Tombol untuk membuka modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#publishModal" id="openModalBtn">
    Publish Your Book (by AJAX)
</button>

<div class="login-info">
    <p>
        You are logged in as : {{ account }} (<a href="{% url 'YourBook:logout' %}">logout</a>)
    </p> 
</div>

<div class="modal fade" id="publishModal" tabindex="-1" role="dialog" aria-labelledby="publishModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="height: auto auto;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="publishModalLabel">Book's Data</h5>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="author">Author:</label>
                        <input type="text" class="form-control" id="author" name="author" required>
                    </div>
                    <div class="form-group">
                        <label for="title">Title:</label>
                        <input type="text" class="form-control" id="title" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="subjects">Subjects:</label>
                        <input type="text" class="form-control" id="subjects" name="subjects" required>
                    </div>
                    <div class="form-group">
                        <label for="language">Language:</label>
                        <input type="text" class="form-control" id="language" name="language" required>
                    </div>
                    <div class="form-group">
                        <label for="bookshelves">Bookshelves:</label>
                        <input type="text" class="form-control" id="bookshelves" name="bookshelves" required>
                    </div>
                    <div class="form-group">
                        <label for="locc">LoCC:</label>
                        <input type="text" class="form-control" id="locc" name="locc" required>
                    </div>
                    <br>
                    <div class="form-group text-center">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="closeModalBtn">Close</button>
                        <button type="submit" class="btn btn-primary" id="button_add">Publish</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script> 

    async function getProducts() {
        return fetch("{% url 'publication:get_buku_user' %}").then((res) => res.json())
    }

    function addProduct() {
        fetch("{% url 'publication:new_publication_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
        }).then(() => {
                refreshProducts();})

        document.getElementById("form").reset()
        return false
    }
    
    document.getElementById("button_add").onclick = addProduct

    refreshProducts()

    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = "";
        const products = await getProducts();
        let htmlString = '<div class="d-flex flex-row flex-wrap">';  // Flex container

        products.forEach((item, index) => {
            const cardClass = index === products.length - 1 ? '' : '';  // Add bg-warning class for the last card
            htmlString += `\n
                <div class="card m-3 ${cardClass}" style="width: 18rem; height:300px; padding: 15px;">
                    <div class="cart-item-product-info" style="height:245px; overflow: scroll;">
                        <h4 class="cart-item-product-title">${ item.fields.title }</h4>
                        <div class="text-lg text-body font-weight-medium pb-1">${ item.fields.author }</div>
                        <div class="text-lg text-body font-weight-medium pb-1">${ item.fields.language }</div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-secondary" type="button" onclick="addToWishlist('${item.fields.Title}')">♡ Wishlist</button>
                    </div>
                </div>`;
        });

        htmlString += '</div>';  // Close flex container
        document.getElementById("product_table").innerHTML = htmlString;
    }

    // Mendapatkan modal
    var modal = document.getElementById('publishModal');

    // Fungsi untuk membuka modal
    function openModal() {
        modal.style.display = "block";
    }

    // Fungsi untuk menutup modal
    function closeModal() {
        modal.style.display = "none";
    }

    // Event listener untuk membuka modal saat button "Add Collection" ditekan
    document.getElementById("openModalBtn").addEventListener("click", openModal);

    // Event listener untuk menutup modal saat tombol "Close" di dalam modal ditekan
    document.getElementById("closeModalBtn").addEventListener("click", closeModal);

    // Event listener untuk menutup modal saat tombol "Add Product" di dalam modal ditekan
    document.getElementById("button_add").addEventListener("click", function() {
        closeModal(); // Menutup modal
        addProduct(); // Memanggil fungsi addCollection 
    });

</script>

{% endblock content %}