YourBook/urls.py
from django.urls import path
from YourBook.views import *
app_name = 'YourBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('logout/', logout_user, name='logout'),
    path('get-product/<str:filter>', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('get_jumlah_item/', get_jumlah_item, name='get_jumlah_item'),
    path('get-product-flutter/', get_product_json_flutter, name='get_product_json_flutter'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
     path('delete-flutter/', delete_item_flutter, name='delete_product_flutter'),
]

bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_bookmark', add_bookmark, name='add_bookmark'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('create-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('remove-bookmark/<int:item_id>', remove_bookmark, name='remove_bookmark'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

gourmet_labs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('YourBook/', include('YourBook.urls')),
    path('review/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
    path("api/books/", include("main.urls")),
    path('publication/', include('publication.urls')), 
    path('bookmark/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_awal, name='show_awal'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('main/', show_main, name='show_main'),
    path("api/books/", get_books, name="get_books"),
    path("add-product-ajax/", add_product_ajax, name="add_product_ajax"),
    path("get-user/", get_user, name="get_user"),
    path("get-buku/", get_buku, name="get_buku"),
     path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

publication/urls.py
from django.urls import path
from publication.views import *

app_name = 'publication'

urlpatterns = [
    path('your-publication/', show_main, name='show_main'),
    path('publication/', new_publication, name='new_publication'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('add-publication-ajax/', new_publication_ajax, name="new_publication_ajax"),
    path('get-buku-user/', get_buku_user, name="get_buku_user"),
    path('new-publication-flutter/', new_publication_flutter, name="new_publication_flutter"),
]

review/urls.py
from django.urls import path
from review.views import *

app_name = 'review'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

wishlist/urls.py
from wishlist.views import show_main, add_wishlist, show_xml, show_json, show_json_by_id, show_xml_by_id, remove_wishlist, add_wishlist_ajax, get_wishlist_json, logout_user, create_wishlist_flutter, delete_wishlist_flutter
from django.urls import path

app_name = 'wishlist'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-wishlist', add_wishlist, name='add_wishlist'),
    path('xml/', show_xml, name='show_xml'), 
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('remove-wishlist/<int:item_id>', remove_wishlist, name='remove_wishlist'), 
    path('create-wishlist-ajax/', add_wishlist_ajax, name='add_wishlist_ajax'),
    path('get-wishlist/', get_wishlist_json, name='get_wishlist_json'),
    path('create-flutter/', create_wishlist_flutter, name='create_wishlist_flutter'),
    path('delete_wishlist_flutter/', delete_wishlist_flutter, name='delete_wishlist_flutter'),
]

YourBook/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Buku
# Create your models here.
class PinjamBuku(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    buku = models.ForeignKey(Buku, on_delete=models.CASCADE)
    petugas = models.TextField()
    judul_buku = models.TextField()
    durasi_pinjam = models.IntegerField()
    catatan_peminjaman = models.TextField()

YourBook/forms.py
from django.forms import ModelForm
from YourBook.models import *

class PinjamBukuForm(ModelForm):
    class Meta:
        model = PinjamBuku
        fields = ["petugas","judul_buku","durasi_pinjam","catatan_peminjaman"]

YourBook/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from YourBook.forms import PinjamBukuForm
from django.urls import reverse
from YourBook.forms import PinjamBuku
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.http import JsonResponse
from main.models import *
import json
# Create your views here.
@login_required(login_url='login/')
def show_main(request):
    try:
        user = User.objects.get(user=request.user)
    except Exception:
        return render(request, "main.html")
    context = {
        'name': request.user.username,
        'class': user.user_type, 
        'id':user.user.pk,
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "pinjam.html", context)
def get_jumlah_item(request):

    jumlah_item = PinjamBuku.objects.filter(user=request.user).count()
    return JsonResponse({'jumlah_item': jumlah_item})

def show_xml(request):
    data = PinjamBuku.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = PinjamBuku.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = PinjamBuku.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = PinjamBuku.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def get_product_json(request, filter):
    user = get_object_or_404(User, user=request.user)
    if user.user_type == "user":
        if filter == 'all':
            products = PinjamBuku.objects.filter(user=request.user)
        else:
            products = PinjamBuku.objects.filter(durasi_pinjam__lt=filter,user=request.user)
    else :
        if filter == 'all':
            products = PinjamBuku.objects.filter()
        else:
            products = PinjamBuku.objects.filter(durasi_pinjam__lt=filter)
    return HttpResponse(serializers.serialize('json', products))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        judul_buku = request.POST.get("judul")
        petugas = request.POST.get("petugas")
        durasi_pinjam = request.POST.get("durasi")
        catatan_peminjaman = request.POST.get("catatan")
        user = request.user

        # Coba untuk mencari buku dengan judul tertentu
        buku = Buku.objects.filter(Title__contains=judul_buku).first()
            
        if not buku:
            return JsonResponse({'status': 'error', 'message': 'Buku tidak ditemukan'}, status=404)
        
        # Buat objek PinjamBuku
        new_product = PinjamBuku(
            buku=buku,
            user=user,
            judul_buku=buku.Title,
            petugas=petugas,
            durasi_pinjam=durasi_pinjam,
            catatan_peminjaman=catatan_peminjaman
        )
        new_product.save()

        return JsonResponse({'status': 'aman', 'message': 'Buku ditemukan'}, status=201)

    return JsonResponse({'status': 'error', 'message': 'Metode permintaan tidak valid'}, status=400)
    
@csrf_exempt
def delete_item(request, id):
    item = get_object_or_404(PinjamBuku, id=id)
    item.delete()
    return JsonResponse({'message': 'Item berhasil dihapus.'})

@csrf_exempt
def get_product_json_flutter(request):
    data = json.loads(request.body)
    filter = data['filter']
    if filter == 'all':
        products = PinjamBuku.objects.filter(user=request.user)
    else:
        products = PinjamBuku.objects.filter(durasi_pinjam__lt=filter,user=request.user)
    return HttpResponse(serializers.serialize('json', products))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)
        buku = Buku.objects.filter(Title__contains=data["judul"]).first()

        new_product = PinjamBuku(
            buku=buku,
            judul_buku = buku.Title,
            petugas = data["petugas"],
            durasi_pinjam = data["durasi"],
            catatan_peminjaman = data["catatan"],
            user = request.user
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def delete_item_flutter(request):
    data = json.loads(request.body)
    item = get_object_or_404(PinjamBuku, id=data['id'])
    item.delete()
    return JsonResponse({'message': 'Item berhasil dihapus.'})

YourBook/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class="container-sm mt-5">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                <div class="bg-info">
                    <div class="card-header">
                        <h1 class="text-center">Login</h1>
                    </div>
                </div>
                <div class="bg-dark text-white">
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username:</label>
                                <input type="text" name="username" placeholder="Username" class="form-control">
                            </div>
    
                            <div class="mb-3">
                                <label for="password" class="form-label">Password:</label>
                                <input type="password" name="password" placeholder="Password" class="form-control">
                            </div>
    
                            <div class="text-center">
                                <input class="btn btn-primary" type="submit" value="Login">
                            </div>
                        </form>
    
                        {% if messages %}
                            <div class="mt-3">
                                <ul class="list-unstyled">
                                    {% for message in messages %}
                                        <li class="text-danger">{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
    
                        <div class="text-center mt-3">
                            Don't have an account yet? <a href="{% url 'YourBook:register' %}" class="btn btn-link">Register Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

YourBook/templates/pinjam.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="{% static 'style1.css' %}">
{% endblock meta %}
{% block content %}
<!-- pada laman ini user dapat meminjam buku dan mengembalikan tetapi hanya dapat melihat buku yg ia pinjam -->
<!-- sedangkan admin dapat melihat seluruh buku yg dipinjam dan juga dapat meminjam buku -->
<!-- judul buku yg dipinjam harus sesuai dengan dataset katalog buku jika tidak sesuai maka akan memberikan modal buku tidak ditemukan -->
<!-- satu buku dapat dipinjam oleh beberapa user -->
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="font-weight: bolder;">GourmetLabs</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
            </li>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown link
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'YourBook:show_main' %}">Pinjam Buku</a></li>
                <li><a class="dropdown-item" href="{% url 'review:show_main' %}">Review</a></li>
                <li><a class="dropdown-item" href="{% url 'wishlist:show_main' %}">Wishlist</a></li>
                <li><a class="dropdown-item" href="{% url 'publication:show_main' %}">Publish</a></li>
                <li><a class="dropdown-item" href="{% url 'bookmark:show_main' %}">Bookmark</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      </nav>

    <div class="card mt-5">
        <div class="card-header bg-dark text-white">
            <h1>Modul Kategori Buku Masak</h1>
        </div>
        <div class="card-body">
            <h5 class="card-title">Name:</h5>
            <p class="card-text">{{name}}</p>
            <h5 class="card-title">Hak akses:</h5>
            <p class="card-text">{{class}}</p>
            <h5 class="card-title">User id:</h5>
            <p class="card-text">{{id}}</p>
            <div class="alert alert-info">
                {{name}} telah meminjam <span id="jumlah_item">{{ jumlah_item }}</span> buku pada aplikasi ini.
            </div>
            <div>
                <label for="filterDropdown">Filter by durasi pinjam (paling lama):</label>
                <select id="filterDropdown" onchange="handleFilterChange()">
                    <option value="all">Show All</option>
                    <option value="7">7 hari</option>
                    <option value="14">14 hari</option>
                    <option value="28">28 hari</option>
                </select>
            </div>
            <table id="product_table"></table>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Pinjam buku</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <p>Silahkan add buku sesuai judul, judul yg terlau panjang dan mengandung enter, karakter lain akibat buruknya dataset bisa diisi subjudulnya saja</p>
                          <p>website ini akan mengambil judul pertama berdasarkan dataset di main page yang mengandung subjudul</p>
                            <form id="form" onsubmit="return false;">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="judul" class="col-form-label">Judul:</label>
                                    <input type="text" class="form-control" id="judul" name="judul"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="petugas" class="col-form-label">Petugas:</label>
                                    <input type="text" class="form-control" id="petugas" name="petugas"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="durasi" class="col-form-label">Durasi Pinjam:</label>
                                    <input type="number" class="form-control" id="durasi" name="durasi"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="catatan" class="col-form-label">Catatan Peminjaman:</label>
                                    <textarea class="form-control" id="catatan" name="catatan"></textarea>
                                </div>
                            </form>
                            <p>Isilah dengan judul yang sesuai dengan dataset katalog buku pada halaman main</p>
                            <p>Buku dengan judul yang tidak valid tidak bisa dipinjam</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Pinjam</button>
                        </div>
                    </div>
                </div>
            </div>
            <div id="myModal"></div>
            <div class="mt-3">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Pinjam Buku</button>
                <a href="{% url 'YourBook:logout' %}" class="btn btn-secondary">Logout</a>
            </div>
            <br />
            <h5>Sesi terakhir login: {{ last_login }}</h5>
        </div>
    </div>
</div>
<script src="{% static 'script1.js' %}"></script>

    
{% endblock content %}