YourBook/urls.py
from django.urls import path
from YourBook.views import *
app_name = 'YourBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('logout/', logout_user, name='logout'),
    path('get-product/<str:filter>', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('get_jumlah_item/', get_jumlah_item, name='get_jumlah_item'),
    path('get-product-flutter/', get_product_json_flutter, name='get_product_json_flutter'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
     path('delete-flutter/', delete_item_flutter, name='delete_product_flutter'),
]

bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_bookmark', add_bookmark, name='add_bookmark'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('create-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('remove-bookmark/<int:item_id>', remove_bookmark, name='remove_bookmark'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

gourmet_labs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('YourBook/', include('YourBook.urls')),
    path('review/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
    path("api/books/", include("main.urls")),
    path('publication/', include('publication.urls')), 
    path('bookmark/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_awal, name='show_awal'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('main/', show_main, name='show_main'),
    path("api/books/", get_books, name="get_books"),
    path("add-product-ajax/", add_product_ajax, name="add_product_ajax"),
    path("get-user/", get_user, name="get_user"),
    path("get-buku/", get_buku, name="get_buku"),
     path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

review/urls.py
from django.urls import path
from review.views import *

app_name = 'review'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

wishlist/urls.py
from wishlist.views import show_main, add_wishlist, show_xml, show_json, show_json_by_id, show_xml_by_id, remove_wishlist, add_wishlist_ajax, get_wishlist_json, logout_user, create_wishlist_flutter, delete_wishlist_flutter
from django.urls import path

app_name = 'wishlist'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-wishlist', add_wishlist, name='add_wishlist'),
    path('xml/', show_xml, name='show_xml'), 
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('remove-wishlist/<int:item_id>', remove_wishlist, name='remove_wishlist'), 
    path('create-wishlist-ajax/', add_wishlist_ajax, name='add_wishlist_ajax'),
    path('get-wishlist/', get_wishlist_json, name='get_wishlist_json'),
    path('create-flutter/', create_wishlist_flutter, name='create_wishlist_flutter'),
    path('delete_wishlist_flutter/', delete_wishlist_flutter, name='delete_wishlist_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Buku(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    Text = models.TextField(null=True, blank=True)
    Type = models.TextField(null=True, blank=True)
    Issued = models.TextField(null=True, blank=True)
    Title = models.TextField(null=True, blank=True)
    Language = models.TextField(null=True, blank=True)
    Authors = models.TextField(null=True, blank=True)
    Subjects = models.TextField(null=True, blank=True)
    LoCC = models.TextField(null=True, blank=True)
    Bookshelves = models.TextField(default="Cookbooks and Cooking")

class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=20)

main/forms.py
from django.forms import ModelForm
from main.models import Buku
from django import forms

class ProductForm(ModelForm):
    class Meta:
        model = Buku
        fields = ["Title", "Authors", "Issued", "Language", "Subjects"]

    Title = forms.CharField(widget=forms.TextInput( attrs={'class':'form-control', }), required=False)
    Authors = forms.CharField(widget=forms.TextInput( attrs={'class':'form-control', }), required=False)
    Issued = forms.CharField(widget=forms.TextInput( attrs={'class':'form-control', }), required=False)
    Language = forms.CharField(widget=forms.TextInput( attrs={'class':'form-control', }), required=False)
    Subjects = forms.CharField(widget=forms.TextInput( attrs={'class':'form-control', }), required=False)

main/views.py
import json
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.http import JsonResponse
from main.forms import ProductForm
from main.models import *
def show_awal(request):
    return render(request, "awal.html")

def show_main(request):
    form = ProductForm(request.POST or None)
    books = Buku.objects.all()
    context = {
        'books': books,
        'form': form,
        'name' : request.user.username,
    }
    return render(request, "main.html", context)

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login') 
        else:
            messages.error(request, 'Invalid Username or Password')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

@csrf_exempt
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_books(request):
    data = Buku.objects.all()
    return HttpResponse(serializers.serialize("json",data), content_type= "application/json")

def get_books_json(request):
    data = Buku.objects.all()
    return HttpResponse(serializers.serialize("json",data))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        user_type = request.POST.get("role")
        user = request.user

        new_product = User(user=user,user_type=user_type)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def get_user(request):
    product_item = User.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def get_buku(request):
    product_item = Buku.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Buku.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/awal.html
{% extends 'base.html' %}

{% block content %}
<style>

#hero {
  width: 100%;
  height: 100vh;
  background: url(../img/hero-bg.jpg) top center;
  background-size: cover;
  position: relative;
}

@media (min-width: 1024px) {
  #hero {
    background-attachment: fixed;
  }
}


#hero .hero-container {
  position: absolute;
  bottom: 0;
  top: 0;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  text-align: center;
}

#hero h1 {
  margin: 30px 0 10px 0;
  font-size: 48px;
  font-weight: 700;
  line-height: 56px;
  text-transform: uppercase;
  color: #fff;
}

@media (max-width: 768px) {
  #hero h1 {
    font-size: 28px;
    line-height: 36px;
  }
}

#hero h2 {
  color: #eee;
  margin-bottom: 50px;
  font-size: 24px;
}

@media (max-width: 768px) {
  #hero h2 {
    font-size: 18px;
    line-height: 24px;
    margin-bottom: 30px;
  }
}

#hero .btn-get-started {
  font-family: "Poppins", sans-serif;
  text-transform: uppercase;
  font-weight: 500;
  font-size: 16px;
  letter-spacing: 1px;
  display: inline-block;
  padding: 8px 28px;
  border-radius: 50px;
  transition: 0.5s;
  margin: 10px;
  border: 2px solid #fff;
  color: #fff;
  text-decoration: none;
}

#hero .btn-get-started:hover {
  background: #2dc997;
  border: 2px solid #2dc997;
}

.navbar {
    border-radius: 50px;
}
.navbar-nav .nav-link:hover {
    background-color: lightgrey;
}

body {
  background-image: url('https://i.ibb.co/nQYv36L/abstract-smooth-blur-background-backdrop-for-your-design-wallpaper-template-with-color-transition-gr.jpg');
  background-size: cover;
  background-repeat: no-repeat;
}
</style>

<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="font-weight: bolder;">GourmetLabs</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_awal' %}">Home</a>
              </li>
          </div>
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-right">
                <li class="nav-item">
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal1">About Us</a>
                </li>
            </ul>
          </div>
        
          <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content text-white" style="background-color:grey; border-radius: 10px;">
                <div class="modal-header border-bottom-0">
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-start px-4 pt-0 pb-4">
                  <div class="text-center">
                    <h3 class="mb-3">About GourmetLabs</h3>
                    <h5 class="mb-5" style="font-weight:lighter">GourmetLabs is an application that provides information, recipes, and engaging reading experiences about culinary cultures from various countries, allowing users to enjoy exclusive culinary-related content.</h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav mx-right">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:login' %}">Login</a>
              </li>
          </div>
        </div>
      </nav>

    <section id="hero">
      <div class="hero-container" data-aos="zoom-in" data-aos-delay="100">
        <h1>Welcome to GourmetLabs</h1>
        <h2>Providing an engaging and enjoyable reading experience with the hope of increasing the interest in reading among the public</h2>
        <a href="{% url 'main:register' %}" class="btn-get-started">Register Now</a>
      </div>
    </section>
    
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}

body {
    background: #ecf0f3;
}

.wrapper {
    max-width: 350px;
    min-height: 500px;
    margin: 80px auto;
    padding: 40px 30px 30px 30px;
    background-color: #ecf0f3;
    border-radius: 15px;
    box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #fff;
}

.logo {
    width: 80px;
    margin: auto;
}

.logo img {
    width: 100%;
    height: 80px;
    object-fit: cover;
    border-radius: 50%;
    box-shadow: 0px 0px 3px #5f5f5f,
        0px 0px 0px 5px #ecf0f3,
        8px 8px 15px #a7aaa7,
        -8px -8px 15px #fff;
}

.wrapper .name {
    font-weight: 600;
    font-size: 1.4rem;
    letter-spacing: 1.3px;
    padding-left: 10px;
    color: #555;
}

.wrapper .form-field input {
    width: 100%;
    display: block;
    border: none;
    outline: none;
    background: none;
    font-size: 1.2rem;
    color: #666;
    padding: 10px 15px 10px 10px;
    /* border: 1px solid red; */
}

.wrapper .form-field {
    padding-left: 10px;
    margin-bottom: 20px;
    border-radius: 20px;
    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;
}

.wrapper .form-field .fas {
    color: #555;
}

.wrapper .btn {
    box-shadow: none;
    width: 100%;
    height: 40px;
    background-color: lightblue;
    color: #fff;
    border-radius: 25px;
    box-shadow: 3px 3px 3px #b1b1b1,
        -3px -3px 3px #fff;
    letter-spacing: 1.3px;
}

.wrapper .btn:hover {
    background-color:lightgrey;
}

.wrapper a {
    text-decoration: none;
    font-size: 0.8rem;
    color:#666;
}

.wrapper a:hover {
    color:black;
}

@media(max-width: 380px) {
    .wrapper {
        margin: 30px 20px;
        padding: 40px 15px 15px 15px;
    }
}
</style>


<div class="wrapper">
    <div class="logo">
        <a href="https://ibb.co/59hVJy8"><img src="https://i.ibb.co/X4xTGgs/c1d7d78a9187bedfe973ac3bc46264fb.jpg" alt="c1d7d78a9187bedfe973ac3bc46264fb" border="0"></a>
    </div>
    <div class="text-center mt-4 name">
        GourmetLabs
    </div>
    <form class="p-3 mt-3" method="POST">
        {% csrf_token %}
        <div class="form-field d-flex align-items-center">
            <span class="far fa-user"></span>
            <input type="text" name="username" placeholder="Username">
        </div>
        <div class="form-field d-flex align-items-center">
            <span class="fas fa-key"></span>
            <input type="password" name="password" placeholder="Password">
        </div>
        <button class="btn mt-3" type="submit" value="Login">Login</button>
    </form>

    {% if messages %}
        <div class="mt-3">
            <ul class="list-unstyled">
                {% for message in messages %}
                    <li class="text-danger">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    
    <div class="text-center fs-6">
        <a href="#"></a> Don't have an account yet? <a href="{% url 'main:register' %}">Sign up</a>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<style>
    .navbar {
        border-radius: 50px;
    }
    .navbar-nav .nav-link:hover {
        background-color: lightgrey;
    }

    body {
      background-image: url('https://i.ibb.co/nQYv36L/abstract-smooth-blur-background-backdrop-for-your-design-wallpaper-template-with-color-transition-gr.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
    }
</style>

<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="font-weight: bolder;">GourmetLabs</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
              </li>
          </div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-right">
                <li class="nav-item">
                  <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal1">Add role</a>
                </li>
            </ul>
          </div>

          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Pilihan Modul
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'YourBook:show_main' %}">Pinjam Buku</a></li>
                  <li><a class="dropdown-item" href="{% url 'review:show_main' %}">Review</a></li>
                  <li><a class="dropdown-item" href="{% url 'wishlist:show_main' %}">Wishlist</a></li>
                  <li><a class="dropdown-item" href="{% url 'publication:show_main' %}">Publish</a></li>
                  <li><a class="dropdown-item" href="{% url 'bookmark:show_main' %}">Bookmark</a></li>
                  <li><a class="dropdown-item" href="{% url 'main:logout' %}">Log Out</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
        <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content text-white" style="background-color:grey; border-radius: 10px;">
              <div class="modal-header border-bottom-0">
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-start px-4 pt-0 pb-4">
                <div class="modal-body">
                  <form id="form" onsubmit="return false;">
                      {% csrf_token %}
                      <label>
                        <input type="radio" name="role" value="user" checked>
                        User
                      </label>
                      <label>
                        <input type="radio" name="role" value="admin">
                        Admin
                      </label>
                  </form>
                  <p>User tidak dapat memilih ulang role jika sebelumnya sudah memilih!</p>
              </div>
              <div class="modal-footer">
                  <button type="submit" id="button_add">Select Role</button>
              </div>
              </div>
            </div>
          </div>
        </div>
      </nav> 
      <h3 style="display: flex; justify-content: center; align-items: center; height: 10vh; color:darkslategray; font-weight: bolder;">WAJIB PILIH ROLE SEBELUM MASUK KE MODUL!</h3>
      <table id="product_table"></table>

<script>
    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        })

        document.getElementById("form").reset()
        return false
    }
    
    document.getElementById("button_add").onclick = addProduct

    async function getProducts() {
        return fetch("{% url 'main:get_buku' %}").then((res) => res.json())
    }

    refreshProducts()
    async function refreshProducts() {
    document.getElementById("product_table").innerHTML = "";
    const products = await getProducts();
    let htmlString = '<div class="d-flex flex-row flex-wrap">';  // Flex container

    products.forEach((item, index) => {
        const cardClass = index === products.length - 1 ? '' : '';  // Add bg-warning class for the last card
        htmlString += `
            <div class="card m-3 ${cardClass}" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Judul: ${item.fields.Title}</h5>
                    <p class="card-text">Author: ${item.fields.Authors}</p>
                    <p class="card-text">Language: ${item.fields.Language}</p>
                </div>
    
                <div class="card-footer">
                  <button class="btn btn-secondary" type="button" onclick="addToWishlist('${item.fields.Title}')">♡ Wishlist</button>
                  <button type="button" class="btn btn-secondary" id="reviewButton">📖 Review</button>
                </div>
                
            </div>`;
    });

    htmlString += '</div>';  // Close flex container
    document.getElementById("product_table").innerHTML = htmlString;

  }

  function addToWishlist(title) {
    const encodedTitle = encodeURIComponent(title);
    const url = "{% url 'wishlist:add_wishlist' %}?title=" + encodedTitle;
    window.location.href = url;
  }



</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}

body {
    background: #ecf0f3;
}

.wrapper {
    max-width: 550px;
    min-height: 500px;
    margin: 80px auto;
    padding: 40px 30px 30px 30px;
    background-color: #ecf0f3;
    border-radius: 15px;
    box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #fff;
}

.logo {
    width: 80px;
    margin: auto;
}

.logo img {
    width: 100%;
    height: 80px;
    object-fit: cover;
    border-radius: 50%;
    box-shadow: 0px 0px 3px #5f5f5f,
        0px 0px 0px 5px #ecf0f3,
        8px 8px 15px #a7aaa7,
        -8px -8px 15px #fff;
}

.wrapper .name {
    font-weight: 600;
    font-size: 1.4rem;
    letter-spacing: 1.3px;
    padding-left: 10px;
    color: #555;
}

.wrapper .form-field input {
    width: 100%;
    display: block;
    border: none;
    outline: none;
    background: none;
    font-size: 1.2rem;
    color: #666;
    padding: 10px 15px 10px 10px;
    /* border: 1px solid red; */
}

.wrapper .form-field {
    padding-left: 10px;
    margin-bottom: 20px;
    border-radius: 20px;
    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;
}

.wrapper .form-field .fas {
    color: #555;
}

.wrapper .btn {
    box-shadow: none;
    width: 100%;
    height: 40px;
    background-color: lightblue;
    color: #fff;
    border-radius: 25px;
    box-shadow: 3px 3px 3px #b1b1b1,
        -3px -3px 3px #fff;
    letter-spacing: 1.3px;
}

.wrapperwarn .btn {
    box-shadow: none;
    width: 100%;
    height: 40px;
    background-color:darkgrey;
    color: #fff;
    border-radius: 25px;
    box-shadow: 3px 3px 3px #b1b1b1,
        -3px -3px 3px #fff;
    letter-spacing: 1.3px;
}

.wrapper .btn:hover {
    background-color:lightgray;
}

.wrapper a {
    text-decoration: none;
    font-size: 0.8rem;
    color: lightgray;
}

.wrapper a:hover {
    color: lightgray;
}

@media(max-width: 380px) {
    .wrapper {
        margin: 30px 20px;
        padding: 40px 15px 15px 15px;
    }
}
</style>

<div class="wrapper">
    <div class="logo">
        <a href="https://ibb.co/59hVJy8"><img src="https://i.ibb.co/X4xTGgs/c1d7d78a9187bedfe973ac3bc46264fb.jpg" alt="c1d7d78a9187bedfe973ac3bc46264fb" border="0"></a>
    </div>
    <div class="text-center mt-4 name">
        GourmetLabs
    </div>
    <form class="p-3 mt-3" method="POST">
        {% csrf_token %}
        <div class="form-field d-flex align-items-center">
            <span class="far fa-user"></span>
            <input type="text" name="username" placeholder="Username">
        </div>
        <div class="form-field d-flex align-items-center">
            <span class="fas fa-key"></span>
            <input type="password" name="password1" placeholder="Password">
        </div>
        <div class="form-field d-flex align-items-center">
            <span class="fas fa-key"></span>
            <input type="password" name="password2" placeholder="Confirm Password">
        </div>
        
        <div style="display: flex; justify-content: center; align-items: center;">
            <a class="btn mt-3" type = "submit" data-bs-toggle="modal" data-bs-target="#exampleModal2" style="width: 120px; margin-right: 20px; background-color: lightcoral; font-size:medium;">Check Me</a>
            <button class="btn mt-3" type="submit" name="submit" value="Daftar" style="width: 250px;">Register Now!</button>
        </div>

        <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content text-white" style="background-color:lightcoral; border-radius: 10px;">
                <div class="modal-header border-bottom-0">
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-start px-6 pt-0 pb-4">
                  <div class="text-center">
                    <h3 class="mb-3">Requirements</h3>
                    <h5 class="mb-5 text-start" style="font-weight:lighter">
                        --- Username ---<br>
                        Required. 150 characters or fewer. Letters, digits, and @/,/+/-/_ only.<br><br>

                        --- Password ---<br>
                        • Your password can't be too similar to your other personal information.<br>
                        • Your password must contain at least 8 characters.<br>
                        • Your password can't be a commonly used password.<br>
                        • Your password can't be entirely numeric.<br>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
        </div>




    
    </form>
</div>

{% endblock content %}